<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Banking.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../gen/csharp/**/*.cs" LinkBase="Generated" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Api.CommonProtos" Version="2.17.0" />
    <PackageReference Include="Google.Protobuf" Version="3.33.5" />
    <PackageReference Include="Grpc.Core.Api" Version="2.76.0" />
  </ItemGroup>

</Project>
